"""Add llm_analysis column

Revision ID: 104d8bc0e838
Revises: 6d9f34b1d861
Create Date: 2026-02-07 14:04:31.009437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104d8bc0e838'
down_revision = '6d9f34b1d861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_analysis', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_analyses', schema=None) as batch_op:
        batch_op.drop_column('llm_analysis')

    # ### end Alembic commands ###
