"""Initial

Revision ID: 6d9f34b1d861
Revises: 
Create Date: 2026-02-07 05:53:54.844809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9f34b1d861'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('discord_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=64), nullable=True),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('champion', sa.String(length=32), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('kda', sa.Float(), nullable=True),
    sa.Column('gold_earned', sa.Integer(), nullable=True),
    sa.Column('gold_per_min', sa.Float(), nullable=True),
    sa.Column('total_damage', sa.Integer(), nullable=True),
    sa.Column('damage_per_min', sa.Float(), nullable=True),
    sa.Column('vision_score', sa.Integer(), nullable=True),
    sa.Column('cs_total', sa.Integer(), nullable=True),
    sa.Column('game_duration', sa.Float(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_analyses_match_id'), ['match_id'], unique=False)

    op.create_table('riot_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summoner_name', sa.String(length=64), nullable=False),
    sa.Column('tagline', sa.String(length=16), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('puuid', sa.String(length=128), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puuid')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('check_interval', sa.Integer(), nullable=True),
    sa.Column('weekly_summary_day', sa.String(length=16), nullable=True),
    sa.Column('weekly_summary_time', sa.String(length=8), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('weekly_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('avg_kda', sa.Float(), nullable=True),
    sa.Column('avg_gold_per_min', sa.Float(), nullable=True),
    sa.Column('avg_damage_per_min', sa.Float(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_summaries')
    op.drop_table('user_settings')
    op.drop_table('riot_accounts')
    with op.batch_alter_table('match_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_analyses_match_id'))

    op.drop_table('match_analyses')
    op.drop_table('discord_configs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
